const names={downtown:'Downtown Boston',backbay:'Back Bay',kendall:'Kendall Square',longwood:'Longwood Medical Area',seaport:'Seaport'};
const keys=Object.keys(names),$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[],towns=[],selected=new Set(),dest='downtown',threshold=45,includeLimited=false,sortKey='town',sortDir=1,filtered=[];
const numeric=['typical_minutes','fastest_minutes','peak_departures'];
function parseCSV(text){const lines=text.trim().split(/\r?\n/);const split=line=>{let out=[],v='',q=false;for(let i=0;i<line.length;i++){let c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++;}else q=!q;}else if(c===','&&!q){out.push(v);v='';}else v+=c;}out.push(v);return out;};const head=split(lines.shift());return lines.map(line=>Object.fromEntries(split(line).map((v,i)=>[head[i],numeric.includes(head[i])?(v.trim()===''?null:Number(v)):v])));}
function valid(r){return numeric.every(k=>Number.isFinite(r[k])&&r[k]>=0)&&r.fastest_minutes<=r.typical_minutes&&!r.duplicate;}
function eligible(r){return r&&valid(r)&&r.contains_destination!=='yes'&&(includeLimited||r.limited_service!=='yes');}
const median=v=>{if(!v.length)return null;const a=[...v].sort((a,b)=>a-b),i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2;};
const pct=(n,d)=>d?`${Math.round(100*n/d)}%`:'—';
function getMetrics(){const base=rows.filter(r=>selected.has(r.town)&&r.destination===dest),good=base.filter(eligible),within=good.filter(r=>r.typical_minutes<=threshold);const common=[...selected].filter(t=>keys.every(d=>eligible(rows.find(r=>r.town===t&&r.destination===d))));const comparison=keys.map(d=>({d,n:rows.filter(r=>common.includes(r.town)&&r.destination===d&&r.typical_minutes<=threshold).length})).sort((a,b)=>b.n-a.n);return{base,good,within,common,comparison,med:median(good.map(r=>r.typical_minutes))};}
function townPicker(){const q=$('search').value.toLowerCase();$('townOptions').innerHTML=towns.filter(t=>t.toLowerCase().includes(q)).map(t=>`<label><input type="checkbox" value="${esc(t)}" ${selected.has(t)?'checked':''}>${esc(t)}</label>`).join('')||'<p>No matching municipalities.</p>';}
function render(){const m=getMetrics(),{base,good,within,common,comparison,med}=m;const local=base.filter(r=>r.contains_destination==='yes').length,limited=base.filter(r=>r.limited_service==='yes').length,excluded=base.length-good.length;const serviceNote=includeLimited?'Limited service included.':'Limited service excluded.';
 $('selectionCount').textContent=`${selected.size} of ${towns.length}`;
 $('filterSummary').textContent=`${names[dest]} · ${selected.size} municipalities selected · typical time ≤ ${threshold} minutes · ${serviceNote} All views use the selected towns; destination comparison and heatmap retain all five destinations.`;
 document.querySelectorAll('[data-min]').forEach(b=>b.classList.toggle('active',Number(b.dataset.min)===threshold));
 $('indicators').innerHTML=[['Median typical journey',`${med??'—'} <small>min</small>`,'Unweighted median across '+good.length+' eligible towns'],['Within '+threshold+' minutes',`${pct(within.length,good.length)}`,`${within.length} / ${good.length} eligible towns`],['Eligible municipalities',`${good.length} <small>/ ${selected.size}</small>`,'For '+names[dest]],['Excluded / flagged',`${excluded} <small>/ ${limited}</small>`,`${excluded} excluded records; ${limited} limited-service flags; ${local} local markers`]].map(([label,value,note])=>`<article class="kpi"><span class="klabel">${label}</span><strong>${value}</strong><p>${note}</p></article>`).join('');
 const top=comparison[0],last=comparison[comparison.length-1],leaders=comparison.filter(x=>x.n===top.n).map(x=>names[x.d]).join(', '),long=good.filter(r=>r.typical_minutes>60),gap=median(good.map(r=>r.typical_minutes-r.fastest_minutes));
 $('findings').innerHTML=`<article class="finding"><b>${common.length?leaders+' '+(comparison.filter(x=>x.n===top.n).length>1?'tie for the lead':'leads'):'No common comparison sample'}</b><p>${common.length?`${top.n} / ${common.length} common towns (${pct(top.n,common.length)}) are within ${threshold} min, versus ${last.n} / ${common.length} for ${names[last.d]}.`:'Select more towns or include limited service to create a shared eligible sample.'} <a href="#explore">Destination comparison ↗</a></p></article><article class="finding"><b>${good.length?`${long.length} towns exceed an hour`:'No eligible journeys'}</b><p>${long.length} / ${good.length} eligible towns (${pct(long.length,good.length)}) exceed 60 min to ${names[dest]}; ${good.length-long.length} are at or below an hour. <a href="#details">Underlying records ↗</a></p></article><article class="finding"><b>${gap??'—'} min median scheduled gap</b><p>Typical minus fastest across ${good.length} eligible town pairs. ${good.filter(r=>r.typical_minutes===r.fastest_minutes).length} have no gap; ${good.filter(r=>r.typical_minutes>r.fastest_minutes).length} do. This is not delay variability. <a href="#options">Scheduled options ↗</a></p></article>`;
 $('recommendations').innerHTML=`<p><b>01 / Evaluate office accessibility</b>${common.length&&top.n>0?`Investigate ${leaders} using the ${top.n} / ${common.length} common towns within ${threshold} minutes as a starting point.`:'The current selection does not distinguish an accessible office option within this threshold. Broaden the selection before drawing a recommendation.'} Workforce distribution, office costs, and first/last-mile travel still need separate evaluation.</p><p><b>02 / Investigate attendance flexibility</b>${long.length} / ${good.length} eligible towns exceed 60 minutes${long.length?' (including '+long.slice(0,3).map(r=>esc(r.town)).join(', ')+')':''}; ${limited} / ${base.length} selected records have sparse service. ${long.length||limited?'Investigate flexible arrival times or hybrid attendance for these journeys.':'This selection supplies no long-journey or sparse-service trigger for a policy change.'} These are questions to investigate, not proven improvements.</p>`;
 $('comparisonNote').textContent=`Within ${threshold} minutes · common sample: ${common.length} towns · ${selected.size-common.length} selected towns excluded because at least one destination is ineligible. ${serviceNote}`;
 $('bars').innerHTML=common.length?comparison.map(({d,n})=>`<div class="barrow"><span>${names[d]}</span><div class="bartrack" role="img" aria-label="${names[d]}: ${n} of ${common.length}, ${pct(n,common.length)}"><div class="barfill" style="width:${n/common.length*100}%"></div></div><span class="barvalue">${pct(n,common.length)} <small>(${n}/${common.length})</small></span></div>`).join(''):'<p class="empty">No towns are eligible for all five destinations. Adjust the municipality or service selection.</p>';
 const ordered=[...selected].sort((a,b)=>$('heatSort').value==='time'?((rows.find(r=>r.town===a&&r.destination===dest&&eligible(r))?.typical_minutes??Infinity)-(rows.find(r=>r.town===b&&r.destination===dest&&eligible(r))?.typical_minutes??Infinity)||a.localeCompare(b)):a.localeCompare(b));
 $('heat').innerHTML=ordered.length?`<table class="heat-table"><caption class="footnote">Typical journey in minutes</caption><thead><tr><th scope="col">Municipality</th>${keys.map(d=>`<th scope="col">${{downtown:'Downtown',backbay:'Back Bay',kendall:'Kendall',longwood:'Longwood',seaport:'Seaport'}[d]}</th>`).join('')}</tr></thead><tbody>${ordered.map(t=>`<tr><th scope="row">${esc(t)}</th>${keys.map(d=>{const r=rows.find(r=>r.town===t&&r.destination===d);if(!r||!valid(r))return'<td title="Unavailable">—</td>';if(r.contains_destination==='yes')return'<td title="Destination within municipality; local travel not estimated">Local</td>';const l=r.limited_service==='yes';if(l&&!includeLimited)return'<td class="limited" title="Limited service, excluded">L · excluded</td>';const v=r.typical_minutes,colors=v<=30?['#e1f2e9','#102f40']:v<=45?['#bce1ce','#102f40']:v<=60?['#80bfa6','#102f40']:v<=90?['#387c68','#fff']:['#164a3e','#fff'];return`<td style="background:${colors[0]};color:${colors[1]}" title="${esc(t)} to ${names[d]}: ${v} minutes${l?', limited service':''}">${v}${l?' L':''}</td>`;}).join('')}</tr>`).join('')}</tbody></table>`:'<p class="empty">No municipalities selected.</p>';
 const ten=[...good].sort((a,b)=>a.town.localeCompare(b.town)).slice(0,10),max=Math.max(60,...ten.map(r=>r.typical_minutes));
 $('dumbbells').innerHTML=ten.length?ten.map(r=>`<div class="dumbrow"><div class="dumbtitle"><b>${esc(r.town)}${r.limited_service==='yes'?' · L':''}</b><span>${r.fastest_minutes} → ${r.typical_minutes} <span class="muted">(Δ ${r.typical_minutes-r.fastest_minutes})</span></span></div><div class="dumbtrack" role="img" aria-label="${esc(r.town)}: fastest ${r.fastest_minutes}, typical ${r.typical_minutes} minutes"><span class="dumbline" style="left:${r.fastest_minutes/max*100}%;width:${(r.typical_minutes-r.fastest_minutes)/max*100}%"></span><span class="dumbpoint fast" style="left:${r.fastest_minutes/max*100}%"></span><span class="dumbpoint" style="left:${r.typical_minutes/max*100}%"></span></div></div>`).join('')+`<p class="footnote">Scale: 0–${max} min · showing ${ten.length} of ${good.length} eligible towns. ${serviceNote}</p>`:'<p class="empty">No eligible scheduled journeys in this selection.</p>';
 filtered=base.filter(r=>includeLimited||r.limited_service!=='yes').sort((a,b)=>{const av=a[sortKey],bv=b[sortKey];return sortDir*(typeof av==='number'?av-bv:String(av??'').localeCompare(String(bv??'')));});
 const cols={town:'Municipality',destination:'Destination',via_station:'Origin station',typical_minutes:'Typical · min',fastest_minutes:'Fastest · min',peak_departures:'Peak departures',limited_service:'Limited service',contains_destination:'Contains destination'};
 $('tableNote').textContent=`${filtered.length} displayed records for ${names[dest]}. ${serviceNote} Local markers remain visible but are excluded from journey summaries. Threshold highlights accessibility; it does not hide slower journeys.`;
 $('table').innerHTML=filtered.length?`<table><thead><tr>${Object.entries(cols).map(([k,label])=>`<th scope="col" aria-sort="${sortKey===k?(sortDir===1?'ascending':'descending'):'none'}"><button data-sort="${k}">${label}${sortKey===k?(sortDir===1?' ↑':' ↓'):''}</button></th>`).join('')}</tr></thead><tbody>${filtered.map(r=>`<tr>${Object.keys(cols).map(k=>`<td${k==='limited_service'&&r[k]==='yes'?' class="limited"':''}>${numeric.slice(0,2).includes(k)&&r.contains_destination==='yes'?'Local — not estimated':k==='destination'?names[r[k]]:esc(r[k]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<p class="empty">No records match this selection. Select municipalities or reset filters.</p>';
 $('download').disabled=!filtered.length;
 return {destination:dest,threshold,selectedTowns:selected.size,eligibleTowns:good.length,withinThreshold:within.length,medianMinutes:med,commonTowns:common.length};
}
function csvDownload(){const columns=['town','destination','typical_minutes','fastest_minutes','via_station','peak_departures','limited_service','contains_destination'];const csv=[columns.join(','),...filtered.map(r=>columns.map(k=>'"'+String(r[k]??'').replace(/"/g,'""')+'"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='filtered-boston-commutes.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function reset(){dest='downtown';threshold=45;includeLimited=false;selected=new Set(towns);$('destination').value=dest;$('threshold').value=45;$('limited').checked=false;$('search').value='';$('heatSort').value='town';sortKey='town';sortDir=1;townPicker();render();}
async function init(){try{const response=await fetch('ma-mbta-commute-times.csv');if(!response.ok)throw Error('The supplied data could not be loaded.');rows=parseCSV(await response.text());const counts={};rows.forEach(r=>counts[r.town+'|'+r.destination]=(counts[r.town+'|'+r.destination]||0)+1);rows.forEach(r=>r.duplicate=counts[r.town+'|'+r.destination]>1);towns=[...new Set(rows.map(r=>r.town))].sort();selected=new Set(towns);const bad=rows.filter(r=>!valid(r)).length,missing=rows.filter(r=>numeric.some(k=>r[k]===null)).length; $('validation').textContent=`File validation: ${rows.length} records, ${towns.length} municipalities, ${new Set(rows.map(r=>r.destination)).size} destinations; ${rows.filter(r=>r.limited_service==='yes').length} limited-service records and ${rows.filter(r=>r.contains_destination==='yes').length} local markers. ${Object.values(counts).filter(n=>n>1).length} duplicate pairs, ${missing} records with missing numeric values, ${bad} records failing numeric/order/duplicate checks. Invalid records are excluded from summaries.`;
 townPicker();render();$('destination').onchange=e=>{dest=e.target.value;render();};$('threshold').oninput=e=>{if(e.target.value!==''&&e.target.validity.valid){threshold=Number(e.target.value);render();}};document.querySelectorAll('[data-min]').forEach(b=>b.onclick=()=>{threshold=Number(b.dataset.min);$('threshold').value=threshold;render();});$('limited').onchange=e=>{includeLimited=e.target.checked;render();};$('search').oninput=townPicker;$('townOptions').onchange=e=>{e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);render();};$('allTowns').onclick=()=>{selected=new Set(towns);townPicker();render();};$('noTowns').onclick=()=>{selected.clear();townPicker();render();};$('reset').onclick=reset;$('heatSort').onchange=render;$('table').onclick=e=>{const b=e.target.closest('[data-sort]');if(b){sortDir=sortKey===b.dataset.sort?-sortDir:1;sortKey=b.dataset.sort;render();}};$('download').onclick=csvDownload;
 const context=document.modelContext;if(context?.registerTool){try{await context.registerTool({name:'configure_commute_comparison',title:'Configure commute comparison',description:'Update destination, time threshold, municipality selection and limited-service inclusion on this dashboard.',inputSchema:{type:'object',properties:{destination:{type:'string',enum:keys},threshold:{type:'number',minimum:1,maximum:300},towns:{type:'array',items:{type:'string'}},includeLimited:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['destination','threshold','towns','includeLimited'].includes(k))||(input.destination!==undefined&&!keys.includes(input.destination))||(input.threshold!==undefined&&(!Number.isFinite(input.threshold)||input.threshold<1||input.threshold>300))||(input.towns!==undefined&&(!Array.isArray(input.towns)||input.towns.some(t=>!towns.includes(t))))||(input.includeLimited!==undefined&&typeof input.includeLimited!=='boolean'))throw Error('Invalid comparison filters');dest=input.destination??dest;threshold=input.threshold??threshold;includeLimited=input.includeLimited??includeLimited;if(input.towns!==undefined)selected=new Set(input.towns);$('destination').value=dest;$('threshold').value=threshold;$('limited').checked=includeLimited;townPicker();return render();}});}catch(e){console.warn('Optional comparison tool unavailable',e);}}
 }catch(e){$('error').textContent=e.message+' Reload the page or download the source CSV.';$('filterSummary').textContent='Data unavailable';}}
init();
